# example docker-compose.yml file
# "cp .docker-compose.yml docker-compose.yml" to use it
version: '3'
services:
  app:
    build: .    
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    networks:
      - redis-net
    depends_on:
      - redis
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.ring.rule=Host(`kronova.net`)"
#      - "traefik.http.routers.ring.entrypoints=websecure"
#      - "traefik.http.routers.ring.tls.certresolver=myresolver"

  redis:
    image: redis:6.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
      - ./docker_data/redis:/usr/local/etc/redis

networks:
  redis-net:

volumes:
  redis-data: